checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 1
  epochs: 10 #200
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/CMultiStepMLM/modelcpu.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/CMultiStepMLM/tmp_modelcpu.pt
  max_steps: 10000
  prefetch_factor: null
  num_workers: 0

# validation:
#   #default: 0.0432 #0.040266551749508626
#   dataset: 'tedlium'
#   split: 'dev'
#   use_cer: true
#   optim_args:
#     lr: 1e-2
#   rollout_fn: singlestep

evaluation:
  dataset: 'tedlium'
  split: 'dev'
  use_cer: false
  epochs: 1

# dataset:
#   load_audio: true
#   clamp_min: null
#   clamp_max: null
#   cer_weight: 0.0
#   wer_weight: 1.0 
#   scale: true
#   standardize_std: false
#   all_zero_to_one: true

collate_function: MultiStep_DTLM
dataset_class: MultiStepDataset

policy:
  lr: 1e-3
  class: ConditionalMultiStepMaskGenerator
  config:
    codebook_size: 2048
    hidden_dim: 512
    embedding_dim: 256
    default_conditioning_reward: 1.0
    audio_vae_state_dict_path: "/mnt/parscratch/users/acp21rjf/l2augment_model/autoenc_audio/model_gpu.pt"
    audio_vae_config:
      latent_dim: 256 # same as default hdim
      use_vq: false
      norm_type: 'bn'
    mask_vae_state_dict_path: "/mnt/parscratch/users/acp21rjf/l2augment_model/bvae/bvae_USINGTHISFORNOW_2048gpu.pt"
    mask_vae_config:
      latent_dim: 128
      codebook_size: 2048
      use_vq: true

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_multistep_cvqmlm"
  optim_args:
    lr: 8e-6
    single_step_lr: 9e-2





  
#this_american_life_566_audio_307200.pt