checkpointing:
  asr_model: /store/store5/data/acp21rjf_checkpoints/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt

training:
  device: cpu
  random_seed: 123456
  batch_size: 1
  epochs: 1
  tolerance: 1
  max_steps: 0
  num_workers: 0
  prefetch_factor: null
  wandb_project: l2augment
  wandb_mode: disabled
  model_save_path: exp/results/repro/reward_conditioned_lm/no_audio_conditioning/smoke/no_audio_reward_conditioned_mask_lm_smoke.pt
  tmp_model_save_path: exp/results/repro/reward_conditioned_lm/no_audio_conditioning/smoke/no_audio_reward_conditioned_mask_lm_smoke_tmp.pt

evaluation:
  id: ROB-114-reward-conditioned-mask-lm-smoke
  dataset: tedlium
  split: dev
  rollout_fn: singlestep
  use_cer: false
  epochs: 1
  augmentation_config:
    conditioning_reward: 1.0
    sample: false
  optim_args:
    lr: 1e-5
  save_path: exp/results/repro/reward_conditioned_lm/no_audio_conditioning/smoke/tedlium_dev_eval_smoke.txt

collate_function: RewardConditionedMaskLM
dataset_class: RewardConditionedMaskLMDataset

dataset:
  reward_metric: wer
  normalization: per_utterance
  degenerate_std_eps: 1e-6

policy:
  lr: 6e-4
  class: RewardConditionedMaskLM
  config:
    hidden_dim: 64
    default_conditioning_reward: 1.0
    reward_encoder: timestep
    sample_generation: false
    mask_vae_state_dict_path: /store/store5/data/acp21rjf_checkpoints/l2augment/models/bvae/bvae_USINGTHISFORNOW_2048gpu.pt
    mask_vae_config:
      latent_dim: 128
      codebook_size: 2048
      use_vq: true

generation:
  save_dir: /store/store4/data/l2augment_rollout_uvqmlm
  train_max_files: 1
  dev_max_files: 1
