checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"


policy:
  class: FrequencyMaskingRanker

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_multistep_FM_rs"
  search_repeats: 8
  rollout_repeats: 8  
  optim_args:
    lr: 6e-6
    single_step_lr: 1e-1
  augmentation_config:
    repeats: 1
    use_random: true  


  
#this_american_life_566_audio_307200.pt