checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 32
  epochs: 100 #200
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/multistep_FM_ranker/modelcpul2.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/multistep_FM_ranker/tmp_modelcpul2.pt
  prefetch_factor: 6
  num_workers: 8

# validation:
#   #default: 0.0432 #0.040266551749508626
#   dataset: 'tedlium'
#   split: 'dev'
#   use_cer: true
#   optim_args:
#     lr: 1e-2
#   rollout_fn: singlestep

evaluation:
  dataset: 'tedlium'
  split: 'dev'
  use_cer: false
  epochs: 2
  optim_args:
    lr: 5e-6

dataset:
  include_audio: false


collate_function: MultiStep_FM_ranker
dataset_class: MultiStepFMDataset

policy:
  lr: 1e-3
  class: MultiStepMaskRanker
  config:
    hidden_dim: 1024
    gru_layers: 2
    condition_on_audio: false
    # audio_vae_state_dict_path: "/mnt/parscratch/users/acp21rjf/l2augment_model/autoenc_audio/model_gpu.pt"
    # audio_vae_config:
    #   latent_dim: 256 # same as default hdim
    #   use_vq: false
    #   norm_type: 'bn'
 

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_multistep_FM/"
  optim_args:
    lr: 8e-6
    single_step_lr: 9e-2





  
#this_american_life_566_audio_307200.pt