checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 84
  epochs: 100
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/ufm/mseloss/model.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/ufm/mseloss/tmp_model.pt

evaluation: 
  dataset: 'this_american_life'
  split: 'test'
  use_cer: false
  epochs: 5
  augmentation_config:
    repeats: 15
    use_random: false
  optim_args:
    lr: 5e-6
  save_path: /users/acp21rjf/learning-to-augment/exp/results/UFMR/TAL.txt

policy:
  lr: 1e-4
  class: UnconditionalFrequencyMaskingRanker

