checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 40  
  epochs: 200
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/bvae/model2048gpu.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/bvae/tmp_model2048gpu.pt


policy:
  lr: 1e-3
  class: BVAE
  config: 
    latent_dim: 128
    codebook_size: 2048

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_mmr9e2/"



  
#this_american_life_566_audio_307200.pt