checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 32
  lr: 1e-5
  epochs: 1
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/model.pt

policy:
  input_dim: 256
  masks_path: /users/acp21rjf/learning-to-augment/l2augment/modelling/mask.pt

generation:
  save_dir: null #  "/mnt/parscratch/users/acp21rjf/l2augment_rollouts/"
  max_steps: 200

