  checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 84
  epochs: 100
  # model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/ufm/mseloss/model.pt
  # tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/ufm/mseloss/tmp_model.pt


evaluation:
  dataset: 'chime6'
  split: 'test'
  use_cer: false
  epochs: 3
  augmentation_config:
    repeats: 1
    use_random: true
  optim_args:
    lr: 8e-7
  save_path: /users/acp21rjf/learning-to-augment/exp/results/NoAug/chime6.txt

policy:
  lr: 1e-4
  class: NoAugmentation

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_2e1/"



  
#this_american_life_566_audio_307200.pt