checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 42 #84
  epochs: 1
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/cm/test/model.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/cm/test/tmp_model.pt

validation:
  #default: 0.040014294573317497
  dataset: 'tedlium'
  split: 'dev'
  use_cer: true
  optim_args:
    lr: 5e-6

evaluation:
  dataset: 'tedlium'
  split: 'dev'
  use_cer: false
  epochs: 1
  optim_args:
    lr: 5e-6

dataset:
  load_audio: true
  clamp_min: null
  clamp_max: null
  cer_weight: 0.0
  wer_weight: 1.0

policy:
  lr: 1e-5
  class: ConditionalMaskingPolicy 
  config:
    hidden_dim: 256
    mel_bins: 80
    output_dim: 80
    vae_config: 
      input_dim: 80
      hidden_dim: 256
      latent_dim: 16
      layers: 5
    vae_state_dict_path: /mnt/parscratch/users/acp21rjf/l2augment_model/vae/model.pt

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_CM/"

collate_function: vae_based_policy


  
#this_american_life_566_audio_307200.pt