_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 23
                - 55
            "4": 3.9.16
            "5": 0.18.7
            "6": 4.36.0
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
