checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 64
  lr: 1e-5
  epochs: 1000
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/model.pt

policy:
  input_dim: 256

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollouts/"

