checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #"/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_4096_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 84
  epochs: 100
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/ufm/multloss/model.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/ufm/multloss/tmp_model.pt

evaluation:
  dataset: 'tedlium'
  augmentation_config:
    repeats: 10
    use_random: true


dataset:
  load_audio: false
  clamp_min: null
  clamp_max: null

policy:
  lr: 1e-4
  class: UnconditionalFrequencyMaskingRanker
  config:
    loss_type: 'mult'

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout/"


  
#this_american_life_566_audio_307200.pt