checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #"/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_4096_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 24
  epochs: 100
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/model.pt

policy:
  lr: 3e-4
value:
  save_path: "/mnt/parscratch/users/acp21rjf/l2augment_value/model.pt"

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout/"

  
#this_american_life_566_audio_307200.pt