checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  random_seed: 1234
  batch_size: 4


policy:
  input_dim: 256
  optim:
    lr: 3e-5

value:
  input_dim: 80
  hidden_size: 256
  optim:
    lr: 1e-3

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollouts/"
