checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 8
  lr: 1e-5
  epochs: 25
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/model.pt

policy: null

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollouts/"
  max_steps: 50


teacher_logits_generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_teacher_logits/"
  asr_checkpoint:  "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb_3epoch/n_seq_sched_4096_rp_1/step_316080.pt"
