training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 84
  epochs: 1000
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/vae/model.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/vae/tmp_model.pt


generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout/"



  
#this_american_life_566_audio_307200.pt