checkpointing:
  asr_model: "/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_2048_rp_1/step_105360.pt"
  #asr_model: "/mnt/parscratch/users/acp21rjf/spotify/checkpoints_seq_scheduler_rb/n_seq_sched_2048_rp_1/step_105360.pt" 
  #"/mnt/parscratch/users/acp21rjf/spotify/rotary_pos_6l_256d_seq_sched/n_seq_sched_4096_rp_1/step_105360.pt"

training:
  device: 'cuda'
  random_seed: 1234
  batch_size: 4
  epochs: 10
  model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/dt/test/best_model.pt
  tmp_model_save_path: /mnt/parscratch/users/acp21rjf/l2augment_model/dt/test/tmp_model.pt
  max_steps: 2500

validation:
  default: 0.0432 #0.040266551749508626
  dataset: 'tedlium'
  split: 'dev'
  use_cer: true
  optim_args:
    lr: 3e-6

evaluation:
  dataset: 'tedlium'
  split: 'dev'
  use_cer: false
  epochs: 1
  optim_args:
    lr: 3e-6

dataset:
  load_audio: true
  clamp_min: null
  clamp_max: null
  cer_weight: 0.0
  wer_weight: 1.0 
  set_minus_or_positive: false
  scale: true
  zero_mean: false
  standardize_std: false
  expand_mask_to_audio: true

policy:
  lr: 1e-3
  class: DTConditionalMaskingPolicy 
  config:
    default_conditioning_reward: 1.0
    hidden_dim: 256
    mel_bins: 80
    output_dim: 80
    audio_vae_config: 
      input_dim: 80
      hidden_dim: 256
      latent_dim: 16
      layers: 5
    mask_vae_config:
      latent_dim: 128
      codebook_size: 64
    audio_vae_state_dict_path: /mnt/parscratch/users/acp21rjf/l2augment_model/vae/model.pt
    mask_vae_state_dict_path: /mnt/parscratch/users/acp21rjf/l2augment_model/bvae/model3.pt

generation:
  save_dir: "/mnt/parscratch/users/acp21rjf/l2augment_rollout_test/"
  return_wer: true
  optim_args:
    lr: 1e-1

collate_function: vae_based_policy


  
#this_american_life_566_audio_307200.pt